{% set name = "aiohttp" %}
{% set version = "2.3.3" %}
{% set sha256 = "0a2e33e90560dacb819b095b9d9611597925d75d1b93dd9490055d3826d98a82" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [py2k]

requirements:
  build:
    - python
    - setuptools
    - toolchain
  run:
    - python
    - chardet
    - multidict >=3.0.0
    - async-timeout >=1.2.0
    - yarl >=0.11

test:
  imports:
    - aiohttp

about:
  home: https://github.com/aio-libs/aiohttp
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: 'Async http client/server framework (asyncio)'

  doc_url: http://aiohttp.readthedocs.io/
  dev_url: https://github.com/aio-libs/aiohttp

extra:
  recipe-maintainers:
    - sodre
    - kszucs
